### PR TITLE
Upgrade/react transition group+others

### LINKED ISSUE #12: Update React TransitionsGroup To solve "componentWillMount has been renamed"
React TransitionGroup is already updated. Here is a really old dep in use -
i checked the guid and changed the Notifications.js the use the TransistionGroup
would be nice to get it updated. 

Thanks

image

Mirgation Guide:
https://github.com/reactjs/react-transition-group/blob/master/Migration.md

src/Notifications.js
```
import React from 'react';
import PropTypes from 'prop-types';
import { CSSTransition, TransitionGroup } from 'react-transition-group';
import classnames from 'classnames';
import Notification from './Notification';

class Notifications extends React.Component {
  static propTypes = {
    notifications: PropTypes.array.isRequired,
    onRequestHide: PropTypes.func,
    enterTimeout: PropTypes.number,
    leaveTimeout: PropTypes.number
  };

  static defaultProps = {
    notifications: [],
    onRequestHide: () => {
    },
    enterTimeout: 400,
    leaveTimeout: 400
  };

  handleRequestHide = notification => () => {
    const { onRequestHide } = this.props;
    if (onRequestHide) {
      onRequestHide(notification);
    }
  };

  render() {
    const { notifications, enterTimeout, leaveTimeout } = this.props;
    const className = classnames('notification-container', {
      'notification-container-empty': notifications.length === 0
    });

    const items = notifications.map((notification,i) => {
        const key = notification.id || new Date().getTime();
        return (
          <CSSTransition
            key={i}
            classNames="notification"
            timeout={{ enter: enterTimeout, exit: leaveTimeout }}
          >
          <Notification
            key={key}
            type={notification.type}
            title={notification.title}
            message={notification.message}
            timeOut={notification.timeOut}
            onClick={notification.onClick}
            onRequestHide={this.handleRequestHide(notification)}
          />
          </CSSTransition>
        );
      })
    return (
      <div className={className}>

        <TransitionGroup >
          {items}
        </TransitionGroup>
      </div>
    );
  }
}

export default Notifications;
```

### PR DESCRIPTION
**Pull request by el-j**
sorry a bit late, but here the request to the next branch

fixes  #12

### CODE REVIEW

**Comment by el-j** [comment]
please check if the build process is working. there are many package upgrades included and i am sadly not able to build it with gulp and babel

**Comment by tjrexer** [comment]
Yea, I'm getting the same problem with build.  Seems to be a breakdown with the `@babel/register` module, can't find additional modules such as `@babel/plugin-proposal-object-rest-spend`.  Verify that all of the modules & all of their requirements are included.

**Comment by el-j** [comment]
...hm maybe you can find out why it's happening? I tried a while to get it to work but I wasn't able to...otherwise maybe just get the code out of my pr for the transition group fix....

https://github.com/tjrexer/react-notifications/commit/23704c64bbe8b6937a3eee2f35649bdf7018d69f

**Comment by tjrexer** [comment]
So after messing with it, there's a couple problems with the setup.  Some of it is due to out of date packages, others are due to linting failures, but you need to update those packages for it to work.  Update the packages listed at the bottom, and then resolve the lint errors.  If you want to close this PR & then open a new one when you get it working that would work, or just work everything in this branch.

I'm going to work on updating packages in the next release, that don't require code changes, in the meantime.  You can give it a shot, if not I'll come back to it after packages are updated.

Packages
```
dependencies:{
    "@types/react-transition-group": "^4.2.0",
    "prop-types": "^15.5.10"
},
devDependencies: {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-register": "^6.26.0",
    "eslint": "^7.7.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.20.6"
}
```

**Comment by tjrexer** [comment]
Alright, I updated a lot of the babel, webpack, & lint components that were causing problems.  The only thing left is getting your fix to work.  Including your new Notifications file, it will successfully build, but then crashes during runtime.  Error received is below.  Simplifies the troubleshooting a lot.  You can either close this PR, and open a new one based off the updated next, or just make the changes in place.  I think all of the other out of date packages are now resolved.

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `TransitionGroup`.
```

**Comment by tjrexer** [comment]
Fixed in v1.7.0

**Pull request closed without merging**
